---
- name: "Install nginx"
  ansible.builtin.apt:
    name: "nginx"
    state: "present"
    update_cache: true

- name: "Copy our config nginx"
  ansible.builtin.copy:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    owner: "root"
    group: "root"
    mode: '0644'
    backup: true

- name: "restart nginx daemon"
  ansible.builtin.service:
    name: "nginx"
    state: "restarted"
    enabled: true